# Generated by Django 5.2 on 2025-04-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default=0, upload_to='static/img/'),
            preserve_default=False,
        ),
    ]
