# Generated by Django 5.2 on 2025-04-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_image',
            field=models.BooleanField(default=False),
        ),
    ]
