# Generated by Django 5.2 on 2025-04-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_image_is_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
