# Generated by Django 5.2 on 2025-04-20 09:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_image_public_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='blog_image_created_1ba45b_idx',
        ),
        migrations.RemoveField(
            model_name='image',
            name='is_image',
        ),
        migrations.AlterField(
            model_name='image',
            name='img_file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='post_images/'),
        ),
    ]
