# Generated by Django 5.2 on 2025-04-20 12:07

import cloudinary.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_image_img_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_file',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='image'),
        ),
    ]
