# Generated by Django 5.2 on 2025-04-20 12:15

import blog.models
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_image_img_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_file',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[blog.models.cloudinary_file_extension_validator], verbose_name='image'),
        ),
    ]
